### ISSUE TITLE
Add function to order snapshot/differential

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#1083]
The snapshot generator is dependent on the order of elements in the differential (as described in the spec).  However, e.g. when manually creating differentials or otherwise producing unordered differentials, it would be useful if the API provides functionality so soft the differential based on the "official" order of the elements.

**Comment by wmrutten** [comment]
We can provide an operation to correct invalid order of regular, non-sliced elements. Slicing is a bit more complicated and poses some requirements on the input. To ensure correct interpretation, a sliced differential must either:
* introduce children of named slices in-order
* OR specify element id's everywhere
Otherwise the element order is ambiguous and cannot be "corrected" automatically.

**Comment by mmsmits** [comment]
I could really really use this as well.

**Comment by brianpos** [comment]
I have a routine that creates the "tree" of ElementDefinitions then serializes back out the flat list to make this sort of thing easier for myself.
I think it requires the list to be correct going in, but I guess that could be changed so that it is a little more forgiving.
https://github.com/brianpos/fhir-distillery/blob/master/fhir.distillery/Processors/ElementDefinitionCollection.cs

**Comment by mmsmits** [comment]
We will reopen once someone needs this.
Sushi, Forge etc do this well, and we don't see people creating SD's manually anymore.
