### ISSUE TITLE
Custom Logical Model datatypes should be represented based on ElementDefiniton.representation

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1221]
A logical model might introduce custom "primitive" datatypes, meaning data types that represent a value using but are build up using FHIR primitive datatypes. The CDA on FHIR project has a couple of these datatypes, e.g. "ST", "ED", or "ON". If a value should be represented by ElementDefintion.representation = xmlText, the API should not assume that the primitive value is stored in an "value" element (See TypedElementOnSourceNode Value Getter). Instead it should check in the StructureDefinition which element has the correct representation attribute set and choose this element for serialisation and parsing.

**Comment by ewoutkramer** [comment]
For reference, let us look at the `ST` structuredefinition:

```
  <element id="ED.data[x]">
      <path value="ED.data[x]"/>
      <representation value="xmlText"/>
      <definition value="The string value"/>
      <min value="0"/>
      <max value="1"/>
      <base>
        <path value="ED.data[x]"/>
        <min value="0"/>
        <max value="1"/>
      </base>
      <type>
        <code value="string"/>
      </type>
    </element>
```

I have taken this from https://build.fhir.org/ig/HL7/cda-core-2.0/branches/master/StructureDefinition-ST.profile.xml.html.  There are a few things to notice here:

* In the structuredefinition, this element (and others) are present twice (not sequentially though, so not a slice) - this is probably an error.
* This is a real constraint, not a new datatype (the path starts with ED as well).
* Is ED.data[x] is "the" value, which we would like to end up in the `TypedElement.Value` ?
* Or is it fine to end up in `data` (which is probably what happens now).
* We need to take care in this case since this attribute is a choice type, and we have not yet had any primitive types in which the `.Value` was a choice type.
* Can we assume that if `representation=xmlText` then this is the `TypedElement.Value`?

**Comment by ewoutkramer** [comment]
Note that this behaviour is also present in the FhirXmlNode - too low level to have metadata like `representation` to decide about this. See also #1270.

**Comment by alexzautke** [comment]
```Is ED.data[x] is "the" value, which we would like to end up in the TypedElement.Value ?```
Yes, that would be the idea.

```Can we assume that if representation=xmlText then this is the TypedElement.Value?```
ST / ED are currently the only data types in which we know that this assumption should be true. Not much to compare to.

**Comment by mmsmits** [comment]
We will not invest in the CCDA stack in combination with ITypedElement anymore.
If the need arises, we are now thinking of writing an XML Parser for CCDA to Poco's specifically.
