### ISSUE TITLE
Run all shared FHIR test cases against our API

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#1262]
It is said that currently we only run 6 of the shared FHIR test cases on the .NET API: https://github.com/FHIR/fhir-test-cases. It would likely be better for the quality of the validator to run all of them in an automated fashion.

Discussion on Zulip:
* Announcements of net test cases: https://chat.fhir.org/#narrow/stream/179297-committers.2Fnotification/topic/FHIR.20Test.20Cases
* Discussion: https://chat.fhir.org/#narrow/stream/179310-firely-tooling/topic/Validator.20comparison and https://chat.fhir.org/#narrow/stream/179166-implementers/topic/HL7.20Validator.20for.20Runtime.20Validation/near/187486249

**Comment by grahamegrieve** [comment]
Not - the test cases are driven from the manifest.json file. The manifest presents a test case, and then defines what the java validator does in terms of errors and warnings. Mostly, it works by count. I expect that the dotnet validator will not produce the same error messages, or even the same count, so I expect that the dotnet validator will have it's own parallel addition to each test case. But I do expect that the validators will agree about what is valid or not 

I will document the format at some stage so that it's easier to get the tests working

**Comment by ewoutkramer** [comment]
(text from @marcovisserFurore)

Snapshot compatibility between .NET and Java. - and Michel's/Grahame's unit-tests.

Ideas:
- make a submodule of the repo from Grahame and perform the unittest on that
- create a build pipeline that downloads the latest version of the data of Grahame and then perform the unittest of that

**Comment by mmsmits** [comment]
This is already in place
