### ISSUE TITLE
How to retry?

### ISSUE THREAD

**Issue by joshmouch** [FirelyTeam/firely-net-sdk#1314]
Since the HttpClient is hidden, I can not figure out how to implement retry logic on FHIR calls.

Is there a way to use IHttpClientFactory or Polly in some other way to add resiliency to FHIR.Net?

**Comment by marcovisserFurore** [comment]
We are implementing a new FhirClient, which will contain the "new" `HttpRequestMessage` and `HttpResponseMessage`. We will expose some parts of this layer to the end user, so that users can also this lower level.

For now, the `HttpClient` is indeed hidden and is not accessible for the end user. 

You can follow this board to see our progress on the new FhirClient:
https://github.com/FirelyTeam/fhir-net-api/projects/9

**Comment by marcovisserFurore** [comment]
The new `FhirClient` can have a `HttpMessageHandler`. With this handler you can influence the `HttpResponseMessage` and inspect the `HttpRequestMessage`.
