### ISSUE TITLE
New error thrown in 4.0.1 that wasn't on 4.0.0 on manually defined slicing rules

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-net-sdk#1336]
Apparently there was a time where "Forge did not correctly constrain value[x] in an extension" so people (at least the German basisprofil) did manual edits after Forge for this. Like element in diff:
```
   {
                "id":"HumanName.family.extension:vorsatzwort.value[x]:valueString",
                "path":"HumanName.family.extension.valueString",
                "sliceName":"valueString"
   }
```
in https://simplifier.net/packages/de.basisprofil.r4/0.9.3-alpha2/files/117980/~json.

This now causes errors in 4.0.1 like the ones in https://simplifier.net/eau/patient-example/$validate:
Error 10012: `The profile should specify the inherited element name 'valueString'.`.

**Comment by mmsmits** [comment]
This issue has arisen due to an error in the FHIR spec that has been fixed in 4.0.1.

In the original 4.0.0. spec, some artifacts that have value[x] elements that were constrained to have a single type. Changed their path to contain that element like: `extension.valueString`. However, the FHIR spec from R4 states that the path of value[x] element don't change (they stay at `extension.valueString`, but just constrain their type to a single element. 

These faulty artifacts (like this particular humanname-own-name extension, have been fixed in 4.0.1.
Therefor the manually added contraints in the german profile containing a path of extenion.valueString, are incorrect after that fix.

This is something we aren't going to allow in SnapshotGenerator, because it is incorrect behavior, and have to be changed in the profiles itself, to comply to the 4.0.1. spec
