### ISSUE TITLE
Transforming of resources before rendering prevents validation on element sequence.

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#1512]
When an instance is rendered on Simplifier the instance is automatically transformed to an element tree by the .NET API. The API puts all the elements in the correct order.

This even happens when pasting the xml directly in the Simplifier validator. The validator does check the element sequence.
Please note that when rendering, the instance is transformed to an element tree by the API. So rendering shows you processed data, while the download gives you the original data. I do think that we need to change this in the API, because this means, that Examples, when downloading could be wrong even though the validator validates true.

**Comment by ewoutkramer** [comment]
I think this is a Simplifier issue, but I am not sure.  The .NET API only reorders the elements when writing the tree back to XML, otherwise it would generate incorrect XML.  Maybe, internally, Simplifier does a XML->tree->XML conversion somewhere.  I am pretty sure we are *not* re-ordering the elements when constructing the tree, since this is very expensive (and not necessary when writing to Json for example).

I'll point the Simplifier guys to this issue, so we can look at it in concert.

**Comment by wardweistra** [comment]
Thanks, continuing here: https://firely.atlassian.net/browse/SIM-1508
