### ISSUE TITLE
Don't reference [System/Microsoft].Net.Http for .NET 4.5+ and don't reference System.ValueTuple for .NET 4.7+

### ISSUE THREAD

**Issue by cbenard** [FirelyTeam/firely-net-sdk#1539]
**Is your feature request related to a problem? Please describe.**
We cannot reference the `Hl7.Fhir.STU3` NuGet without pulling in `System.ValueTuple` and `System.Net.Http`.

**Describe the solution you'd like**
The csproj files should add the `net47` target and change the `Condition` attributes to correctly exclude `System.ValueTuple` for `net47` and exclude `System.Net.Http`/`Microsoft.Net.Http` for `net45` and `net47`.

This also applies to the `common` submodule.

**Describe alternatives you've considered**
Adding `<ExcludeAssets>all</ExcludeAssets>` to the `<PackageReference />`.

**Additional context**
Immo has a [Twitter thread](https://twitter.com/terrajobst/status/997262020108926976) explaining the history of the Http NuGet packages and Framework and clearly states that now they shouldn't be used. They're only kept updated for people who took a dependency on them before since they don't want to break existing code.

@joperezr also has [a comment](https://github.com/microsoft/dotnet/issues/889#issuecomment-430466436) that is pretty clear on it as well.

They should be removed where they can.

`ValueTuple` is not necessary in .NET 4.7+ since it is built-in so this obviously should not be a dependency in NuGet either for this platform, but currently only `net45` is supported so `net47` should be added to exclude this dependency.

Thank you.

**Comment by ewoutkramer** [comment]
I don't think our reorganization (although beneficial) actually solves this problem.

All our targets still reference System.ValueTuple, so referencing the SDK from 4.7 will still reference ValueTuple.

But I don't like the ("easy") solution of adding another target. Every target means longer compilation times, more test runs, larger nugets, and more platform to install for every contributor.  I want less platforms, not more.

This seems to be the same issue (but then for another open source project): https://github.com/morelinq/MoreLINQ/issues/348

So - before System.ValueTuple 4.4, you used not to be able to compile and use the libraries, but after 4.4, this was solved in System.ValueTuple itself.  I agree with the maintainer of MoreLINQ (see the issue referenced above):  if the only problem is that we reference one package too many on 4.7, but everything works fine otherwise, we should not add a new target. 

But if there are some other disadvantages that we have not discussed, we might reconsider.
