### ISSUE TITLE
search by identifier, parse string to Date by the library

### ISSUE THREAD

**Issue by DominaTang** [FirelyTeam/firely-net-sdk#1559]
**Describe the bug**
When pass query parameter as "identifier=202012106188", the search method throw exception:
"Hl7.Fhir.ElementModel.StructuralTypeException
  HResult=0x80131537
  Message=Type checking the data: Literal '2020-01-11T05:00:00.000Z' cannot be parsed as a date. (at Bundle.entry[0].resource[0].item[5].answer[0].valueDate[0])
  Source=Hl7.Fhir.Support.Poco"

Some other identifier value doesn't throw exception.  It seems Fhirly.Net SDK try to parse the parameter to DateTime, however this is a string value.
If directly query the FHIR server with "identifier=202012106188" with postman, there is no problem to return the data, so it seems it is a bug in Fhirly-Net-SDK itself.

**Version used:**
 - FHIR Version: R4
 - Version: 2.0.1, 2.0.0

**Comment by marcovisserFurore** [comment]
Hi @DominaTang . Thanks for reaching out to us.

I think the problem is not the search parameter itself, but the response you get back from the FHIR Server. Look at the exception information:
```
Message=Type checking the data: Literal '2020-01-11T05:00:00.000Z' cannot be parsed as a date. (at Bundle.entry[0].resource[0].item[5].answer[0].valueDate[0])
```

So there is a resource (the first resource in the response bundle), that has an answer with value of type `Date` (probably a `QuestionnaireResponse`). That date cannot be parsed by the SDK because it contains a datetime instead of only a date. So the SDK cannot create a Poco because it cannot construct a correct property (`QuestionnaireResponse.Answer[0].ValueDate`).

Unfortunately the FHIR server contains a non validated resource.

**Comment by DominaTang** [comment]
Yes, you are right. It's QuestionnaireResponse, we had a Angular client lib written by a vendor, it has no problem to read the record. Or using postman directly query the record,  However, I checked that QuestionnaireResponse data, it's valueDate but with time part. I will check Angular code which write the data.
Thank you so much!

**Comment by dustinmoris** [comment]
I am having the same issue.

The problem is that the (official) Microsoft FHIR server in Azure which we use saved patient's date of births as a DateTime in the past and now a new application that uses the `FhirClient` cannot search for patients due to this validation error in this library.

Even setting the `parserSettings.TruncateDateTimeToDate ` doesn't help:

```
var parserSettings = ParserSettings.CreateDefault();
		parserSettings.TruncateDateTimeToDate = true;
		parserSettings.PermissiveParsing = true;
		
		var fhirClient =
			new FhirClient(
				fhirServerUrl,
				new FhirClientSettings
				{
					PreferredFormat = ResourceFormat.Json, 
					PreferredReturn = Prefer.ReturnRepresentation,
					ParserSettings = parserSettings
				});
```

How can we use the `FhirClient` to work with a FHIR Server which has some historic records with DateTimes in a Date field?
