### ISSUE TITLE
Type mismatch for ExplanationOfBenefit object model between Hl7 R4 Spec and Firely .NET API Hl7.Fhir.R4 (1.9.0)

### ISSUE THREAD

**Issue by pvnmurthy** [FirelyTeam/firely-net-sdk#1587]
Bug description:

**ExplanationOfBenefit.diagnosis.diagnosis** is a CodeableConcept type in HL7 R4 spec where as in case of Firely .NET Hl7.Fhir.R4(1.9.0) this is an Element. Similarly, **ExplanationOfBenefit.procedure.procedure** is a CodeableConcept type in HL7 R4 where as in case of Firely .NET Hl7.Fhir.R4(1.9.0) this is an Element.

**Expected behavior**
We expect that Hl7 R4 V4.0.1 spec for ExplanationOfBenfit object model should match with Firely .NET Hl7.Fhir.R4(1.9.0).

**Version used:**
 - FHIR Version: R4
 - Version: 1.9.0

**Comment by marcovisserFurore** [comment]
It is not completely true: in the standard [Hl7 R4 spec](http://hl7.org/fhir/stu3/explanationofbenefit.html) you can see that the type of `ExplanationOfBenefit.diagnosis.diagnosis` is not only `CodeableConcept` but also a `Reference` type. This is a so called choice type: multiple datatypes are allowed. That's why the type is `Element`, the base type (in version 1.9.0). 

Have a look at https://docs.fire.ly/firelynetsdk/model/choice-properties.html where we explain how you could assign a datatype to a choice type.

In your example it would be:
```c#
                    var codeable = new CodeableConcept("a system", "code");
                    var benefit = new ExplanationOfBenefit();
                    var diagnosis = new ExplanationOfBenefit.DiagnosisComponent() { Diagnosis = codeable };
                    benefit.Diagnosis.Add(diagnosis);
```

**Comment by pvnmurthy** [comment]
Thanks for clarifying and providing the pseudo code.
