### ISSUE TITLE
ITypedElement Select Type question

### ISSUE THREAD

**Issue by whyfate** [FirelyTeam/firely-net-sdk#1643]
**Describe the bug**
`ConceptMap` Select `source-uri` return type is `string`?

**To Reproduce**
The `source` property of `Group` under `ConceptMap` is of `URI` type in `StructureDefinition`,`reference` type in `SearchParameter`,but `string` type in the SDK.

![image](https://user-images.githubusercontent.com/13515020/109253079-ef607380-7829-11eb-9628-dea6db82a775.png)

```csharp
typeElement.Select("ConceptMap.group.source").First().InstanceType; // uri
typeElement.Select("(ConceptMap.source as uri)").First().InstanceType; // System.String
```

**Comment by marcovisserFurore** [comment]
Hi @whyfate, thanks for your feedback on the Firely .NET SDK.

We are investigating this at the moment. The following unittest supports your question:

```c#
[TestMethod]
public void Issue_1643()
{
    var poco = new ConceptMap
    {
        Group = new List<ConceptMap.GroupComponent>() { new ConceptMap.GroupComponent() { Source = "http://example.com" } },
        Source = new FhirUri("http://example.com")
    };

    var typedElement = poco.ToTypedElement();

    Assert.AreEqual("uri", typedElement.Select("ConceptMap.group.source").First().InstanceType); // uri
    Assert.AreEqual("uri", typedElement.Select("ConceptMap.source as uri").First().InstanceType); // System.String
}
```

**Comment by whyfate** [comment]
Thinks

**Comment by marcovisserFurore** [comment]
Using the `As` cast fails only in the case of primitives:

```c#
[TestMethod]
public void Issue_1643()
{
    var poco = new ConceptMap
    {
        Identifier = new Identifier("system", "value"),
        Source = new FhirUri("http://example.com"),
        DateElement = FhirDateTime.Now()
    };

    var typedElement = poco.ToTypedElement();

    Assert.AreEqual("Identifier", typedElement.Select("ConceptMap.identifier").First().InstanceType); // Identifier
    Assert.AreEqual("Identifier", typedElement.Select("ConceptMap.identifier as Identifier").First().InstanceType); // Identifier

    Assert.AreEqual("dateTime", typedElement.Select("ConceptMap.date").First().InstanceType); // dateTime
    Assert.AreEqual("dateTime", typedElement.Select("ConceptMap.date as dateTime").First().InstanceType); // System.DateTime

    Assert.AreEqual("uri", typedElement.Select("ConceptMap.source").First().InstanceType); // uri
    Assert.AreEqual("uri", typedElement.Select("ConceptMap.source as uri").First().InstanceType); // System.String
}
```

The FhirPath specification of this function (http://hl7.org/fhirpath/N1/#as-type-specifier) states:

> this operator returns the value of the left operand if it is of the type specified in the second operand

the *value* of the left operand is the value of `Concept.source`, which is a primitive and has System types. 

@ewoutkramer: what do you think? Do we do something wrong here, or are we following the spec?

**Comment by ewoutkramer** [comment]
This has to do with the "auto-cast" facility of FhirPath:  in most situations when you navigate to a property, you want to cast the FHIR primitive (e.g. boolean) to a FhirPath primitive.  e.g.  `Patient.active = true` is something you'd like to work, although the left-hand side of the equation is a FHIR Primitive (and thus has extension, id , etc) while the right-hand side is a FhirPath primitive.  The cast is not hard: the FHIR primitive types have an implicit `value` field that is of the correct FP primitive type (these were harmonized a few years ago, see http://hl7.org/fhir/fhirpath.html#types).

So, `Patient.active` of type FHIR.Boolean actually turns into `Patient.active.value` of type System.Boolean, and is then compared to `true` (of type System.Boolean).  Success!

ConceptMap.source is of type FHIR.uri.  So, ConceptMap.source = 'some uri' should work, since the FP type of FHIR.uri.value is System.String.   It seems that our `as` operator somehow not only selects the types of type FHIR.uri but also casts them to their FHIRPath primitive.  This is incorrect, I'd say as we're not implicitly referring to the `value` member here.

Both calls should give the same answer, and we should try not to surface System.String anywhere, as this is mostly an implementation detail.

**Comment by ewoutkramer** [comment]
I just read the section at http://hl7.org/fhir/fhirpath.html#types again.  It does say something interesting:

```
Patient.name.given.as(FHIR.string);
Patient.name.given.as(System.string);
```

should both be succesful, so the `as` operator should do a cast if asked for it.  Still, in the case of the OP, we're not asking for a cast.  We might as well fix this too when we're at it ;-)

**Comment by ewoutkramer** [comment]
> It seems that our as operator somehow not only selects the types of type FHIR.uri but also casts them to their FHIRPath primitive. This is incorrect, I'd say as we're not implicitly referring to the value member here.

@kennethmyhra discovered this is done in the `UnboxTo()` function.
