### ISSUE TITLE
Bundle Patch operation does not seem to work

### ISSUE THREAD

**Issue by pvnmurthy** [FirelyTeam/firely-net-sdk#1646]
I want to replace the ExplanationOfBenefit.insurance[0].coverage element with the following data absent reason using BUNDLE PATCH operation.

"insurance": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueString": "Unknown"
        }
      ]
    }

I am using the Firely .NET SDK <PackageReference Include="Hl7.Fhir.R4" Version="2.0.3" />

My code below may not be correct. Please help resolve this issue.....

Here is my code...

            _fhirClient ??= await _fhirService.GetFhirClient().ConfigureAwait(false);
            var trb = new TransactionBuilder(_fhirClient.Endpoint, Bundle.BundleType.Transaction);
            Parameters parameters = new Parameters();
            parameters.AddDeletePatchParameter("ExplanationOfBenefit.insurance[0].coverage");

            Coding cd = new Coding("http://hl7.org/fhir/StructureDefinition/data-absent-reason", "Unknown");
            parameters.AddAddPatchParameter("ExplanationOfBenefit.insurance[0]","extension", cd);
            trb.Patch("ExplanationOfBenefit", "cb51d7f5-2804-4cd3-b86c-f9a30fb27840", parameters);

            var json = trb.ToBundle().ToFormattedJson();

            var resp = await _fhirClient.TransactionAsync(trb.ToBundle()).ConfigureAwait(false);

Any help would be highly appreciated. Thanks in advance.

**Comment by pvnmurthy** [comment]
I am using Firely .NET SDK V2.0.3. I missed to mention it earlier.

**Comment by marcovisserFurore** [comment]
Hi @pvnmurthy  thanks for using the Firely .NET SDK. 

You use the patch operation here. Mind you, that not all Fhir servers are supporting this operation.

In detail,  I see that you try to 
- delete the `coverage` element
- add an extension element on the first element of `insurance`.

which ends up in an incorrect  `ExplanationOfBenefit` resource. Because according to the [standard](https://www.hl7.org/fhir/explanationofbenefit-definitions.html#ExplanationOfBenefit.insurance.coverage), `coverage` is a mandatory element and cannot be empty (cardinality is `1..1`).

So your patch operation is not allowed.

**Comment by pvnmurthy** [comment]
Thanks for your response. I am closing this issue.
