### ISSUE TITLE
LocalTerminologyService - ValueSetValidateCode should check system parameter

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#1651]
**Is your feature request related to a problem? Please describe.**
If ValueSetValidateCode is called with a "code" parameter, the local terminology service should reject the request if no "system" parameter is provided as well.

Description of the "code" parameter:
"The code that is to be validated. If a code is provided, a system or a context **must** be provided (if a context is provided, then the server SHALL ensure that the code is not ambiguous without a system)"

See http://hl7.org/fhir/valueset-operation-validate-code.html.

It would be a nice enhancement if the caller of the API wouldn't need to check this.

**Comment by ewoutkramer** [comment]
This will break our service, since we have always allowed this. I am pretty sure the spec says somewhere that in that case the code should just be available in the valueset, regardless of system.  I think this will also break validating a normal string with a binding.

**Comment by ewoutkramer** [comment]
As we don't have a context, there's not much else you can do.

**Comment by ewoutkramer** [comment]
Wouldn't it be good enough if we do this:
* With a codesystem -> unchanged
* Without a codesystem -> find ALL matches in VS.  If matches have different valuesets -> complain.

Note that it's perfectly fine for a VS to contain the same code/system combi multiple times, so we should really check for multiple different systems.

**Comment by mmsmits** [comment]
Couldn't we just check if either a systen, context,  or valueset is present for now? Also for the external terminology service.

**Comment by ewoutkramer** [comment]
After the standup we concluded:
* We should not use a temporary solution in the LocalTerminologyService, since when we reach out to a properly implemented external terminology service, this might become an issue again.
* So: the validator should supply a context when there is no system (this is possible since the validator has the profile url under validation + the element path).
* The Local terminology service will need to validate the requirement to have a system OR a context
* The Local terminology service will then ignore the context parameter but will do the check for ambiguous codes in the valueset as described above.
