### ISSUE TITLE
Backward parsing compatibility for resources with Date

### ISSUE THREAD

**Issue by Ivanidzo4ka** [FirelyTeam/firely-net-sdk#1691]
**Describe the bug**
I'm working on service which uses currently 1.9 libraries of SDK. We parse incoming resources, and save them into database as plain text (we do other things to extract search information) 1.9 library doesn't have validation for date/datetime difference. 
So we can easily accept something like this:
```
{
  "resourceType": "Patient",
  ...
  "birthDate": "1991-02-03T11:22:33Z"
}
```

We working on moving to 3.0 libraries, and at some point in our pipeline (let's say user requests object from DB) we take plain text from database and deserialize it into object.  Since 2.* libraries has validation on top of date fields I get back parsing exception:
```
resource = JsonParser.Parse<Resource>(str);

Error occurred when parsing model: 'Type checking the data: Literal '1932-09-24T11:22:33Z' cannot be parsed as a date. (at Resource.birthDate[0])'.
```

- I can't scan all databases and fix date representation.

-  I can try to put try catch block around parser check for exception type, parse exception by location, and date content, apply regex to extract date out of datetime, convert string to json, find exact node by location, replace value, and do it in a loop because some resource like `Evidence` can have multiple dates. That solution feels extremely brittle for me, I rely on exception type, exception message format, any change in them would cause me to rewrite code.

- I would like to have ParserSetting option to automatically convert DateTime to Date which would be turn off by default:
something like this:
```
new ParserSettings() { AutomaticDateConversion = true }
```

I don't mind to send PR with such changes, but I would like to hear would you be interested in accepting that change?

https://github.com/microsoft/fhir-server/pull/1743#issuecomment-797827925

**To Reproduce**
```
           var oldValidResource = @"{
  ""resourceType"": ""Evidence"",
  ""approvalDate"": ""1991-02-03T11:22:33Z"",
  ""date"": ""1991-02-03T11:22:33Z"",
  ""lastReviewDate"": ""1991-02-04T11:22:33Z""
}";
FhirJsonParser JsonParser = new FhirJsonParser(DefaultParserSettings.Settings);
var resource = JsonParser.Parse<Resource>(oldValidResource);
```

**Expected behavior**
I would like to have setting which I can specify to make sure I can parse previously valid resource into object.

**Version used:**
 - FHIR Version: [All]
 - Version: [2.*]

**Comment by brianpos** [comment]
I take it this means the content wasn't validated before it was stored creating this issue...
(I've also been burnt by this also)
There is some current discussion around the serializers/parsers to support replacing with alternative implementations that can do things like this (I'm personally doing one for XML and Gino is doing one for JSON, however there is no current timeline for when these will be available.

**Comment by brianpos** [comment]
For this specific issue, where you know which field is the problem, you could do the json update of the content and trim the patient birthdate down to just the 10 chars ;) before passing it to the serializer.

**Comment by Ivanidzo4ka** [comment]
>I take it this means the content wasn't validated before it was stored creating this issue...

I would like to disagree. Content was validated by FhirParser, and was considered as valid before. Which lead to the fact what we ingress who know how much badly formatter resources. This resources are still bring value, and I'm all for not accepting new resources with datetime instead of date, I would like to have option to work with resources I previously ingress.

I don't ask for custom parser, all I'm asking is backward compatibility for current one. 

>For this specific issue, where you know which field is the problem, you could do the json update of the content and trim the patient birthdate down to just the 10 chars ;) before passing it to the serializer.

```
private static readonly Regex MessageChecker = new Regex("Type checking the data: Literal '(.*)' cannot be parsed as a (.*). \\(at (.*)\\)", RegexOptions.Compiled);
        

                    Resource resource = null;

                    Parse:
                    try
                    {
                        resource = JsonParser.Parse<Resource>(str);
                    }
                    catch (StructuralTypeException ex)
                    {
                        var match = MessageChecker.Match(ex.Message);
                        if (match.Success && match.Groups.Count == 4 && match.Groups[2].Value == "date")
                        {
                            var valueToReplace = match.Groups[1].Value;
                            var location = match.Groups[3].Value;
                            var replace = valueToReplace.Substring(0, 10);
                            var root = FhirJsonNode.Parse(str, "Resource");
                            var currentNode = root;
                            while (currentNode != null)
                            {
                                foreach (var child in currentNode.Children())
                                {
                                    if (location.StartsWith(child.Location))
                                    {
                                        currentNode = child;
                                        break;
                                    }
                                }

                                if (currentNode.Location == location)
                                {
                                    break;
                                }
                            }

                            (currentNode as FhirJsonNode).JsonValue.Value = replace;
                            str = root.ToJson();
                            goto Parse;
                        }
                    }
```

Look how brittle that code is. I'm heavily rely on regex parsing of exception, it's a pain to work with location (if you know better way to get to FhirJsonNode by it's location, I'm all ears), I have to do parsing multiple times because there can be multiple dates.

**Comment by brianpos** [comment]
I don't disagree with you, and have felt this pain too in other areas (and had these fixed in the past, permissive parsing was the setting, however that doesn't permit the date parse issue that you've noted here from working).

The point I was making with the validation is that the parser isn't the validator.
There is a Fhir Validator that performs the full validation over the serialization format - which checks way more than the wire format - checking if enumeration values are valid, mandatory fields present, conditional invariants, terminology coding values valid, field formats - dates/times/etc (and much more too)

**Comment by Ivanidzo4ka** [comment]
>The point I was making with the validation is that the parser isn't the validator.

Well, it acts as one now, at least for dates.

We had `DotNetAttributeValidation` running on top of resources, and I bring FHIR validator recently, but it has it's own flaws (at least in 1.9, like give it profile in meta which is not present and resource become invalid).

**Comment by ewoutkramer** [comment]
> Content was validated by FhirParser, and was considered as valid before. 
That's right. It's just that in 2.0+, we rewrote the parsers for the primitive types to align exactly with the spec, they were too lenient. This is of course the usual problem we have and will see whenever we fix a "bug".

> The point I was making with the validation is that the parser isn't the validator.
Unfortunately, the situation is not so binary between parsing and validation. Especially when we are reading into POCO's, there's a minimum set of requirements we need to meet to be able to get stuff into the POCO's.  We decided that "permissive" parsing was the way to go - it basically means the parsers turn everything off except the bare minimum to be able to parse data into POCO's.

Which leaves the corner cases like invalid enum values, invalid dates, invalid decimals etc - basically the primitives. The .NET types can represent more than FHIR allows, so we can be more lenient here - and clearly were so before 2.0 for dates.

Looking at the PR (https://github.com/FirelyTeam/firely-net-common/pull/111), I tend to think we should maybe make this dependent on the existing "PermissiveParsing" switch. We have discussed in the past having more fine-grained control between "exact parsing" and "permissive parsing" -- but decided to make it an all or nothing for now.  Would you be happy with that?

There is of course another chance of data loss here, we're truncating the date, so a roundtrip will fail. Do we that is acceptable?

**Comment by ewoutkramer** [comment]
Ok, let's wrap things up.

The main point of the issue -which we cannot fix easily- is this, and I quote @brianpos :

> The point I was making with the validation is that the parser isn't the validator.

That's right. It must be clear that the parser will allow *many* things not allowed by the spec. This is intentional, validating everything is too expensive for most purposes.  For example, we are not validating the XHTML in the narrative inside resources, nor are we running a terminology service by default to validate non-required code bindings.

There is a thing like "full validation" using the FhirValidator, as Brian mentioned. But I also agree that full validation might still be too much (or too little: many validation rules are only available as narrative in the spec and are not enforced either).

Which leaves the parser between a rock and a hard place.  Allow "everything"?  Not an option - we'll help proliferate absurdly incorrect instances. Do full validation? Way to compute intensive.  So, in the past, and also in discussion with @brendankowitz and @brianpos we've opted for a "PermissiveParsing" option.  Which dialled down the amount of validation done by the parser to an "acceptable" albeit arguably still somewhat arbitrary set of basic rules.  And this "PermissiveParsing" has been the default option used by our server and I am pretty sure Microsoft's too.  

But this is true too:
> I don't ask for custom parser, all I'm asking is backward compatibility for current one

It was never the intention to make permissive validation more strict in 3.x, but we clearly had a bug there before - we did validate date/dateTime but simply not thoroughly enough. As we run a server product ourselves, we understand the pain of having a database full of instances that you cannot parse anymore. So, something 's got to give. 

I suggested turning validation off completely for datetimes (and maybe others) as part of "PermissiveParsing". It's the easy route: you're not creating problems with existing resources. But this might cross the line for the kind of basic validation we do expect from the parser.

**Comment by ewoutkramer** [comment]
What we'll want is a more granular control over validation features. But I am not ready to take that discussion on - yet. Not for this release at least.  So I propose I'll pull @lvanidzo4ka 's PR, and enable it when using PermissiveParsing only.  So, this means we'll get backward compat by default (no specific setting), but also that we'll not enforce full correct "dates" for now.  We're not hurting anyone by doing that, and I don't think a point release (3.3 in this case) is a good place to make bold moves.

**Comment by ewoutkramer** [comment]
Another subtlety:

```
 // TruncateToDate converts 1991-02-03T11:22:33Z to 1991-02-03+00:00 which is not a valid date!
```

At the moment in time I was writing ElementModel.Types.Date, FHIR did not allow timezones on dates, but CQL did, so I had to support both. But this has been aligned, and yes, it would now not be correct anymore. Taking support for dates with timezones out would break the public surface now.  Who said maintaining an SDK was fun?

**Comment by ewoutkramer** [comment]
@Ivanidzo4ka - I worked on this today.  A few remarks:

* I mentioned using PermissiveParsing - I had forgotten that this is for the first phase of parsing (json/xml to SourceNode) only, so we don't have that available for ISourceNode->ITypedElement (or to Poco).  So, I locally pulled your PR with the new setting as you suggested.
* I have check out 1.9 and looked at the behaviour.  If we do it as you suggest, we're not compatible with 1.9. In 1.9, this datetime will be parsed, and retained in its entirety in the Date.Value:

This is the test for 3.x:

```
        [TestMethod]
        public void AllowParseDateWithDateTime()
        {
            var patientJson = "{ \"resourceType\": \"Patient\", \"birthDate\": \"1991-02-03T11:22:33Z\" }";
            var parser = new FhirJsonParser();

            //   Assert.ThrowsException<StructuralTypeException>(() => parser.Parse<Patient>(patientJson));

            parser = new FhirJsonParser(new ParserSettings { AllowDateTimeInDate = true });
            var patient = parser.Parse<Patient>(patientJson);
            Assert.AreEqual("1991-02-03", patient.BirthDate.ToString());
        }
```

If I would port this test back to 1.9, it would fail:

```
 AllowParseDateWithDateTime
   Duration: 735 ms

  Message: 
    Assert.AreEqual failed. Expected:<1991-02-03>. Actual:<1991-02-03T11:22:33Z>. 
  Stack Trace: 
    SerializationTests.AllowParseDateWithDateTime() line 605
```

As you can see, the time is not truncated in 1.9.   Shall we not keep exactly the same behaviour for 3.3?

**Comment by Ivanidzo4ka** [comment]
Thank you for looking into this, and sorry for delayed reply.

Yes, there is no way to fit datetime into date field, I understand that. And I think it's a good thing overall. 

Is it bad what time got cut off? In my context of using that flag only when I read data we already store in DB to return back to user, I don't think it's bad thing to do, that would make data more valid as an output which can be passed further the line.

And maybe one day we will run routine on top of all our databases to cleanup date fields and I don't have to do extra moves with current behavior to clean date, it would happen automatically.

All I want is not to write monstrosity code like that one: https://github.com/FirelyTeam/firely-net-sdk/issues/1691#issuecomment-825157966 

it's super brittle, it's catches one exception at the time, and overall it's something I don't want to have in codebase.

**Comment by ewoutkramer** [comment]
Just for our reference, I'll document the differences between 1.9 and 2.0+:

## 1.9
In 1.9, the text for primitive values was parsed using `XmlConvert.ToXXXX()`, where XXXX was the native .NET type used by the FHIR Poco to represent its `value`.  So, a `FhirBoolean` would use `XmlConvert.ToBoolean()` for its `bool` value element.  This was done by the `PrimitiverTypeConverter`, called from `TypedElementOnSourceNode.Value`.   Date/times used the newer `PartialDate` and `PartialDateTime` classes, but in the end, these two were just using `XmlConvert.ToDateTimeOffset` for parsing, so did not enforce any rules on the presence of a time part (in fact, since `DateTimeOffset` needs a time part, a time part was added to it).  Then, when the POCO was constructed, the `PrimitiveValueReader` would use the parsed representation. Exceptions were made for `PartialDate` and `PartialDateTime` since these are not used in the POCOs, `FhirDateTime` and `Date` both use string. So in the end, the parsed `DateTimeOffset` was turned into a string again and used as a value on these POCO classes.

## 2.0+
Phew. As you can see, this had grown a bit into a mess over the past 10 years. Originally, the FHIR serialization was faithful 100% to the XML Schema type definitions, but as we had to align with the syntax in FhirPath, CQL and the mapping language, we added a few more constraints on them, not reflected in `XmlConvert`.

So, for 2.0+, I introduced a parse flow where `TypedElementOnSourceNode.Value` uses the newly introduced CQL/System primitives (in Hl7.Fhir.ElementModel.Types) for *all* parsing duties, and it does not use `XmlConvert` anymore. This allowed us to align 100% with the latest versions of the specs.  Of course, when building the POCOs in `PrimitiveValueReader`, we still had to turn these into strings for `FhirDateTime` and `Date`, so that remained unchanged.  But these newer classes did enforce exact alignment with the spec, hence the new validation errors.

**Comment by ewoutkramer** [comment]
Now, to @Ivanidzo4ka's point - there's actually two issues:

1. We don't accept the incorrect date+time values anymore for FHIR dates - this breaks existing code.
2. We have a bunch of existing data in our database that was accepted but now cannot be parsed anymore as a consequence of (1). Since running conversions on all our customers databases is infeasible, we need to be able to read & fix this "on the go".

To point 1) We allowed ourselves a breaking change here, it was a major release after all. And I think we agree that this is actually a bugfix, so the default behaviour should be to enforce a correct date/time. We do that for boolean literals, for numerics etc, regardless of "permissive parsing".  I know @brianpos is looking for a way to get this data, even if incorrect, passed through, maybe all the way into the POCO's.  That is not possible currently and is a change too big to make now.  We do pass this incorrect data via `ISourceNode`, and it would be conceivable we could configure the parsers to pass it on to `ITypedElement.Value` as well. But not yet into the pocos.

To point 2) The proposed solution in the PR means truncation of data. So we would indeed need a new, explicit setting, so the developer who wants this truncation indicates he/she *really* wants this to happen. The advantage is that we will not accept incorrect data anymore, and old data will be "refreshed" into valid data automatically.  I can imagine that there might be developers who just want the old behaviour (don't truncate), so we *could* turn the boolean setting in the PR into an enum to specify either "truncate" or "pass-through" behaviour.  But as we all know, every feature has a cost in maintenance and debugging, so if we can avoid that, that might be better.

So my intention is to just pull the PR, maybe change the name of the setting to make even more clear that this will truncate data, unless brighter ideas pop up here in the coming days.
