### ISSUE TITLE
PreferCompressedResponses Not Handled Properly

### ISSUE THREAD

**Issue by kfrancis** [FirelyTeam/firely-net-sdk#1876]
**Describe the bug**
We've been using "PreferCompressedResponses" for a while now, since the output from the service we're communicating with is quite verbose. Recently, on just checking that updates haven't caused issues with functionality - it seems that if we PreferCompressedResponses now, we get a parsing error that we can't recover from `'0x1F' is an invalid start of a value.`  When we change that to `false`, the issue goes away (though it takes much longer).

**To Reproduce**
Not sure how this could be reproduced. I don't think there's anything specific about the responses from this service that might make a difference.

Response Headers:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/fhir+json; charset=utf-8
Expires: -1
Server: 
X-LobTxId: da495b6b-4d68-4e19-bd30-8e7d42947445
X-AspNet-Version: 
X-Powered-By: 
Date: Mon, 13 Sep 2021 17:53:42 GMT
X-Request-Id: 3640dd51613f902507dbaff3
X-Correlation-Id: 23f181de-17a0-41e0-9984-7d255ecafb89
Access-Control-Expose-Headers: X-LobTxId
Access-Control-Expose-Headers: X-Request-Id, X-LobTxId, X-Correlation-Id
X-Global-Transaction-ID: 3640dd51613f902507dbaff3
X-RateLimit-Limit: name=1200perMinRate,1200;
X-RateLimit-Remaining: name=1200perMinRate,1199;
Content-Length: 664245
```

I suspect that the issue here is that the service isn't returning Content-Encoding and so it doesn't know that the content needs deflate, gzip but I'm not sure how (or if) this can be overcome.

**Version used:**
 - FHIR Version: STU3
 - Version: 3.0.0-3.5.0

**Additional context**

Here's the full stack trace.
```
    System.Text.Json.JsonException: '0x1F' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at Hl7.Fhir.Rest.TaskExtensions.WaitResult[T](Task`1 task)
   at Hl7.Fhir.Rest.BaseFhirClient.Search[TResource](SearchParams q)
```

**Comment by marcovisserFurore** [comment]
Hi @kfrancis,

Thanks for using our SDK. I had a look in our source code and I did some investigation on the internet about `Accept-Encoding` (because that is what the setting `PreferCompressedResponses` does: adding `Accept-Encoding` to the request headers). 

It looks like that the response you get from the service is compressed and our `FhirClient` is not decompressing it. From .Net Core 2.0 the default for `HttpClientHandler.AutomaticDecompression` is `DecompressionMethods.None` ([source](https://github.com/dotnet/runtime/issues/21214)). 
In our `FhirClient` we are setting the `AutomaticDecompression` to `DecompressionMethods.GZip | DecompressionMethods.Deflate` for the default HttpClientHandler, but when you are using your own handler you should set the `AutomaticDecompression` yourself. So like this:

```c#
  var handler = new HttpClientHandler()
            {
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
            };

  var client = new FhirClient(endpoint, setttings, handler);
```

Could that be the case in your solution?

Otherwise can you check how the response looks like in Postman? Does the response header  have the value `Content-Encoding` or not?

**Comment by kfrancis** [comment]
It does have `Content-Encoding` but only `gzip` I believe.

Bingo, that did the trick! Oh, you just saved tons on bandwidth.
