### ISSUE TITLE
Fhir Element Order values wrong for Url in Extension.cs

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/firely-net-sdk#1920]
The `Extension.url` order attribute value should not be 30, as this is used in output generation and must be written before the `Element.extension` element as it is an attribute. Maybe change it's order value to 15?
https://github.com/FirelyTeam/firely-net-common/blob/3f94b54bc264f41cc0216ea7022935b60fd76626/src/Hl7.Fhir.Support.Poco/Model/Extension.cs#L66

https://github.com/FirelyTeam/firely-net-common/blob/3f94b54bc264f41cc0216ea7022935b60fd76626/src/Hl7.Fhir.Support.Poco/Model/Element.cs#L70

**Version used:**
 - FHIR Version: all
 - Version: Found in 3.6.0

**Additional context**
This effects anything that uses the order property during processing, or in my case code generation.

**Comment by marcovisserFurore** [comment]
@brianpos : are you sure that this is needed? See here the class hierarchy (including the order attribute):

![image](https://user-images.githubusercontent.com/31658535/144016354-d26ecde6-115c-46f9-baf8-670247a42063.png)

When I create a custom extension you will get the following:

![image](https://user-images.githubusercontent.com/31658535/144017559-b37e7e6e-69a5-47b1-9811-0ef086ecb05a.png)

For me this looks right.

**Comment by ewoutkramer** [comment]
The problem doesn't have to do with the order per se, but with the XML serialization and the fact that your are probably using the .NET `XmlWriter`, so you are probably facing the problem that you need to write out the attributes first, and then the elements.

I would think that this can be fixed by either a double pass over the list of elements (first the attributes, then another pass for the elements), or by sorting the list of elements by the tuple (attribute/element + order), to get the attributes first.  Unless I am misunderstanding this, you will always need to sort anyway, since reflection or the Children/NamedChildren will list the Base's (Element) children first, and then the Extension's children.  If you are already running a sort, can't we find out a way to sort the attributes first and then the rest?

**Comment by brianpos** [comment]
Not a showstopper for me, as I can code around it, was just a surprise to see the order outx and this is the only one.

**Comment by marcovisserFurore** [comment]
Closing this issue, because there is a workaround for this issue and the possibility to introduce breaking changes.
