### ISSUE TITLE
Question: Filters in valueset error

### ISSUE THREAD

**Issue by CaitlinV39** [FirelyTeam/firely-net-sdk#1956]
We are running into an issue with our $validate function against this valueset https://hl7.org/fhir/us/core/ValueSet-detailed-race.json.html where a user is getting the error: Terminology service failed while validating code '1586-7' (system 'urn:oid:2.16.840.1.113883.6.238'): ConceptSets with a filter are not yet supported

https://github.com/FirelyTeam/firely-net-sdk/blob/e9c81270684568833adbc680ba4adf1b86376689/src/Hl7.Fhir.Specification/Specification/Terminology/ValueSetExpander.cs#L117

I can see where this error is thrown above but am wondering if you could help me understand why it gets thrown? I can also see that the valueset I referenced has a filter, so curious if this just isn't supported or if we are potentially doing something wrong.

This is the section of the valueset that has a filter: 

"compose" : {
    "include" : [
      {
        "system" : "urn:oid:2.16.840.1.113883.6.238",
        "filter" : [
          {
            "property" : "concept",
            "op" : "is-a",
            "value" : "1000-9"
          }
        ]
      }
    ],

**Comment by ewoutkramer** [comment]
No, you're not doing something wrong, we just cannot handle valuesets for which the includes specify a filter.  When we designed the basic embedded terminology service that is included with the SDK, we had a pretty common set of requirements in mind, since we don't want to develop a full-blown terminology service.  Filters is where we draw (one of the) lines. 

It's certainly not impossible to extend the functionality a bit: certainly for codesystems that are represented in full in the fhir specification, we can look at the parent/child relationships and create such a filter. But it would not work for say, Snomed, for which you would need a fully loaded snomed set, including closure tables to make this performant.

So, it is possible to enhance the current SDK with a "is-a" filter, but then again, still limited to simpler coding systems.  But to be perfectly honest, it's not on our own priority list, so we would need someone in the community to do it.

**Comment by brianpos** [comment]
And given the way that this is done, I would not suggest that we do it in this implementation, it's not going to really be suitably performant/efficient.
