### ISSUE TITLE
Serialization of Bundle does not work

### ISSUE THREAD

**Issue by wilsonchenbhs** [FirelyTeam/firely-net-sdk#2017]
To improve the performance, we would like to use caching for the result we've already 
fetched and processed.

We've tried different serialization solutions (Newtonsoft Json.NET / System.Text.Json / even the obsolete BinaryFormatter), all complains about the following issue during deserialization:

> Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize readonly or fixed size dictionary: Hl7.Fhir.Model.Bundle. Path 'id', line 1, position 6.'

<img width="299" alt="image" src="https://user-images.githubusercontent.com/95388682/159920378-b63a9c81-8b88-4df8-9051-860c83e2fc5a.png">

This also happens to `DomainResource`.

Does POCOs like `Bundle` in Firefly SDK support serialization/deserialization at all?

**Comment by ewoutkramer** [comment]
FHIR's serialization rules (especially those for Json) are too complex to use the generic Newtonsoft/System.Text.Json serializers.

That's why we have provided specific serializers for FHIR, see https://docs.fire.ly/projects/Firely-NET-SDK/parsing.html.

That being said, the 4.0 version of the SDK (now in beta) *will* integrate better with System.Text.Json (by providing an implementation of `JsonConvert<T>` containing the FHIR-specific serialization rules) and that implementation has been fully optimized for serialization speed.

If you are interested we can give you a pre-release version of 4.0.0 + prelim documentation to try it out.

**Comment by wilsonchenbhs** [comment]
@ewoutkramer  you are right! It's a slip of mind, as we are already using JsonSerializerOptions().ForFhir() / FhirXmlSerializer, we can just use the output and cache it and get it back.

All good. Thanks!

**Comment by oldefezziwig** [comment]
@ewoutkramer , @brianpos , https://www.nuget.org/packages/Hl7.Fhir.STU3 shows that this version is compatible with .NET 4.5.2 or higher, but reading https://docs.fire.ly/projects/Firely-NET-SDK/parsing/system-text-json-serialization.html and looking at this code:
`var jsonInput = "{.....}";
var options = new JsonSerializerOptions().ForFhir(typeof(Patient).Assembly);
var patient = JsonSerializer.Deserialize<Patient>(jsonInput, options);`

That .ForFhir extension method has a compiler directive that requires either .NET 5 or .NET standard 2.0?  We are on .NET 4.8 which should be compatible per the Nuget package info above and can't currently move to .NET 5, but also need to be able to serialize/deserialize so is that supported for .NET 4.8 even though the compiler directive makes the ".ForFhir" extension unavailable when our build target is .NET 4.8?

**Comment by brianpos** [comment]
If that's the case then you probably need to stay with the older JSON serializers till you can move up (my project has been using those forever too)
If you're server side, this is my older JSON serializer in action.
https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.WebApi.Owin/JsonFhirFormatter.cs#L49
https://github.com/brianpos/fhir-net-web-api/blob/feature/r4b/src/Hl7.Fhir.WebApi.Owin/JsonFhirFormatter.cs#L77

**Comment by marcovisserFurore** [comment]
From Firely .NET SDK 4.x we support the following target frameworks: `net6.0`, `net452` and `netstandard2.0`. Since System.Text.Json is not available for net452, we don't support the new serializer and deserialzers for net452.

Like @brianpos said, you can still use the "old" Json serializers/deserializer, which works perfectly fine. The difference with the new ones, is that the new ones are faster. See for the documentation about the classical serializer [here](https://docs.fire.ly/projects/Firely-NET-SDK/parsing/poco-serialization.html).

**Comment by oldefezziwig** [comment]
@brianpos , @marcovisserFurore thanks for the info but we are still getting the same Newtonsoft.Json.JsonSerializationException as mentioned in the beginning of this issue.  Also thanks for confirming that if we stick with a target of .NET 4.8 that we need to stick with "classic serialization" (using Newtonsoft) so we are trying to focus on getting that working

Here is our code, which I thought from your previous comments should still be supported in fhir-net-sdk 4.x?
`      // Create serializer settings
      var serializerSettings = new JsonSerializerSettings
      {
        ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
        NullValueHandling = NullValueHandling.Ignore,
        Formatting = Formatting.Indented,
        ContractResolver = new EmptyCollectionContractResolver(),
        ObjectCreationHandling = ObjectCreationHandling.Replace
      };

      serializerSettings.Converters.Add(new FhirConverter());
      serializerSettings.Converters.Add(new StringEnumConverter());

      // Serialize a CodeableConcept
      var codeableConcept = new CodeableConcept("system", "value");
      var s = JsonConvert.SerializeObject(codeableConcept, serializerSettings);

      // Deserialize a CodeableConcept
      var deserializedCodeableConcept = JsonConvert.DeserializeObject<CodeableConcept>(s, serializerSettings);`

but the last line throws the following Newtonsoft.Json.JsonSerializationException:
`Cannot deserialize readonly or fixed size dictionary: Hl7.Fhir.Model.CodeableConcept. Path 'coding', line 2, position 11.`

Is there something we need to add or change about the JsonSerializerSettings or override something with Newtonsoft?  If you say that "classic" Newtonsoft serialization/deserialization is still supported then there must be a way to accomplish this.

**Comment by marcovisserFurore** [comment]
Hi @oldefezziwig,

I meant with "classical" serializer, the following classes  `FhirJsonSerializer` and `FhirJsonParser`. Your example would then be:

```c#
      // Serialize a CodeableConcept
      var codeableConcept = new CodeableConcept("system", "value");
      var serializer = new FhirJsonSerializer(new SerializerSettings() { Pretty = true });
      var s = serializer.SerializeToString(codeableConcept);

      // Deserialize a CodeableConcept
      var parser  = new FhirJsonParser();
      var deserializedCodeableConcept = parser.Parse<CodeableConcept>(s);
```

**Comment by oldefezziwig** [comment]
Ok thanks @marcovisserFurore.  Looks like we *are* actually using FhirJsonSerializer and FhirJsonParser, so in the above code the class `FhirConverter` is defined as follows (a subclass of Newtonsoft.Json.JsonConverter):
```
  public class FhirConverter : JsonConverter
  {
    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
      var s = new FhirJsonSerializer();
      s.Serialize((Resource) value, writer);
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
      if (reader.TokenType == JsonToken.Null) return null;
      var s = new FhirJsonParser();
      return s.Parse(reader, objectType);
    }

    public override bool CanConvert(Type objectType)
    {
      return typeof(Resource).IsAssignableFrom(objectType);
    }
  }
```
This worked in fhir-net-sdk 3.x but now throws that exception.  I forgot that we needed to use JsonConvert because what we are serializing/deserializing is our own class that has fhir-net-sdk POCOs *in it*.

**Comment by marcovisserFurore** [comment]
I reproduced your case and I also got this error message. This is because the `CanConvert` is `false` for `CodeableConcept`. This element is a datatype and no `Resource`. If you change the `CanConvert` to:
```c#
    public override bool CanConvert(Type objectType)
    {
      return typeof(Base).IsAssignableFrom(objectType);
    }
```
and `WriteJson` to
```c#
 public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
      var s = new FhirJsonSerializer();
      s.Serialize((Base) value, writer);
    }
````
then your unit test will succeed.

`Base` is the root element for all the FHIR poco's, so also for `DataType` and `Resource`.
