### ISSUE TITLE
Unresolvable extension leads to invalid validation error

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#2105]
**Describe the bug**
Validating the the attached bundle will result in an OperationOutcome containing the following error (next to other errors):

```
        {
            "severity": "error",
            "code": "invalid",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
                        "code": "1003"
                    }
                ],
                "text": "The declared type of the element (Group-Fhir4.0) is incompatible with that of the instance ('Patient-Fhir4.0')"
            },
            "location": [
                "Bundle.entry[0].resource[0]",
                "Bundle.entry[3].resource[0].subject[0]"
            ]
        },
```

If you remove all extensions from the Patient resource (first resource in the bundle), the validation will succeed. This indicates that the error does not have anything to do with the reference listed in the OperationOutcome.

**Expected behavior**
Error message should explain better why it's being reported or erroneous error message is removed from the OperationOutcome. 

**Screenshots**

**Version used:**
 - FHIR Version: [e.g.R4]
 - Version: [e.g. 3.x]

**Comment by alexzautke** [comment]
[Delana41_Dibbert990_364ed7c3-055d-4b09-bd7a-270823b916a4.json.zip](https://github.com/FirelyTeam/firely-net-sdk/files/8800210/Delana41_Dibbert990_364ed7c3-055d-4b09-bd7a-270823b916a4.json.zip)

**Comment by brianpos** [comment]
I've had this issue too, and to resolve it I ensured that the extensions that are in the resource are resolvable.
Seems odd, but that's what it is.

**Comment by ewoutkramer** [comment]
> If you remove all extensions from the Patient resource (first resource in the bundle), the validation will succeed. This indicates that the error does not have anything to do with the reference listed in the OperationOutcome.

The reference in the OperationOutcome actually points to the first entry in the bundle, so they are connected.  And then our code batches up the validation against a possible targetprofile on the reference with the url of the extension - I suspect something fishy is going on there.

But I don't understand where the "Group-Fhir4.0" is coming from - according to the SDK code this is either the StructureDecinition.Url or SD.Id.  I am not aware the core definitions use this.  Is there a profile this instance is run against in play?

**Comment by ewoutkramer** [comment]
I ran this test and it returns 1799 errors ;-)  If we stick to the core of the issue, these are the relevant error messages shown around the issue that the OP mentioned:

Overall result: FAILURE (3 errors and 0 warnings)

```
[ERROR] Unable to resolve reference to profile 'http://synthetichealth.github.io/synthea/quality-adjusted-life-years' (at Bundle.entry[0].resource[0].extension[0])
[ERROR] Validation of this resource has been performed before with a failure result. (at Bundle.entry[1].resource[0].subject[0])
[ERROR] The declared type of the element (Group) is incompatible with that of the instance ('Patient') (at Bundle.entry[0].resource[0] via Bundle.entry[1].resource[0].subject[0])
[INFORMATION] Combined ANY validation failed, 2 child validation runs failed, 0 succeeded (at Bundle.entry[0].resource[0] via Bundle.entry[1].resource[0].subject[0])
```

What happens here is that the validator tries to validate the reference (in the original message, `Bundle.entry[3].resource[0].subject[0]`) and since this is `Encounter.subject`, there are several choices, amongst which Patient and Group.

The validator tries all of them, and reports the errors found - unfortunately the instance does not validate against any of the choices, so it reports that the "Combined ANY failed". I agree this is probably the worst error message we have in the validator.  It also means that any of the errors above it are caused by the validator trying out the different possibilities (and failing at all of them), so you will see totally irrelevant ones as well (like the Group one).

The reason that I elaborate on this point is that
a) This will disappear once unresolvable extensions become WARNINGS
b) To explain to all of us why this is the way it is
c) We have improved this in the new validator - it will check the instance type and then *know* it should not validate against Group.  

I do not feel like back-porting that fix, it's pretty substantial. But I will try to improve the ANY error message for this issue.

**Comment by ewoutkramer** [comment]
This is the best I can do:

```
[ERROR] Unable to resolve reference to profile 'http://synthetichealth.github.io/synthea/quality-adjusted-life-years' (at Bundle.entry[0].resource[0].extension[0])
[INFORMATION] Combined validation against the target references failed, 2 child validation runs failed, 0 succeeded. Details follow below (at Bundle.entry[0].resource[0] via Bundle.entry[1].resource[0].subject[0])
   [ERROR] Validation of this resource has been performed before with a failure result. (at Bundle.entry[1].resource[0].subject[0])
   [ERROR] The declared type of the element (Group) is incompatible with that of the instance ('Patient') (at Bundle.entry[0].resource[0] via Bundle.entry[1].resource[0].subject[0])
```

We a) a failure to resolve the profile (via entry[0])
b) A failure to match any of the target references on Encounter.subject (reached via entry[1].resource[0].subject[0])
c) Details of that failure (now indented): 1) a match against Patient, which fails to find the profile on url on an extension in that patiet (BTW that validation is not run again to save time in bundles), 2) a failed match against Group
