### ISSUE TITLE
Cannot modify certain Resource properties when iterating over Children

### ISSUE THREAD

**Issue by IlIlIllIllI** [FirelyTeam/firely-net-sdk#2333]
**Describe the bug**
When iterating over `Base.Children`, certain properties are wrapped in `FhirString` or `FhirUri` when they're returned, and the actual backing properties are just of type `string`.  If you modify these objects they won't be reflected in the object you're iterating over.  I provided some examples that were found, but this may be occurring in other places as well.

**To Reproduce**
`Narrative` example:
1. Create a `Narrative` object: `var narrative = new Narrative { status = Narrative.NarrativeStatus.Generated, div = "original" };`
2. Loop over all children:
   * ```
      foreach(Base child in narrative.Children)
      {
         if (child is IValue<string> childString)
         {
              childString.Value = "new"
         }
      }
      ```
3. `narrative.div` should equal `"new"`, but it equals `"original"` instead.

**Expected behavior**

`Children` should return properties as they are instead of wrapping them when called.

- `Narrative.div` should be of type `FhirString`
  - https://github.com/FirelyTeam/firely-net-common/blob/5899ce463f6cf166520cbbe6322310940942f81c/src/Hl7.Fhir.Support.Poco/Model/Narrative.cs#L203
- `Extension.url` should be of type `FhirUri`
  - https://github.com/FirelyTeam/firely-net-common/blob/5899ce463f6cf166520cbbe6322310940942f81c/src/Hl7.Fhir.Support.Poco/Model/Extension.cs#L141

**Version used:**
 - FHIR Version: R4
 - Version: 3.5.0, Latest

**Comment by ewoutkramer** [comment]
I can see we designed this for read-only indeed. Hard to change, since this 
* has been around for 5-10 years - it will impact a lot of people
* we cannot return the original property, since these are the exceptions in the model: they are primitive .NET types, not subclasses of Base, and Children() needs to return a Base (that's the reason they are being wrapped).


I don't know if this is possible, but if you would change the property "one level up" (so when encountering the Narrative property in its parent Resource), you could simply set `Narrative.Div` instead of going down into `Narrative`?

**Comment by RLPHRE** [comment]
The example I gave was a basic one, as our code was doing a lot more, but yes this is what we did to work around the issue.

Is there any reason why `Narrative.Div` can't be a `FhirString`?

**Comment by RLPHRE** [comment]
> we designed this for read-only

Can you expand on this as well?  Why would these properties be read-only?

**Comment by ewoutkramer** [comment]
I don't remember anymore. This is the oldest code of the SDK. Probably because that was just what we needed ourselves ;-)

**Comment by ewoutkramer** [comment]
> Is there any reason why Narrative.Div can't be a FhirString?
 
If it would be anything, it's probably XHtml - that is what the type is according to the spec.  But this is a very exceptional part of the FHIR spec: it is not really XHtml either, since it's supposed to be "XML" (when thinking about the XML serialization), so it can never have extensions, and it's not rendered as a value attribute.  Because it was so exceptional (just like Extension.url for example), we decided to not represent it as the XHtml type, but as a basic string instead.

Well, that's what I remember, @brianpos might remember even more ;-)

**Comment by ewoutkramer** [comment]
Answered, closing.

**Comment by ewoutkramer** [comment]
Indeed, changing this behaviour will break stuff thats been around for very long, so I have no intention to change it!

**Comment by brianpos** [comment]
I think it is working as expected too, and needn't be changed, the type is that you've walked into the exceptional Narrative type and it's div value isn't a FhirString, it is a primitive string.
Also, back at the top you've stated that certain properties are "wrapped" in a FhirUri or FhirString, this isn't exactly right, that's the FHIR type that they are referring to, and then walks into the value property on them which represents the actual value of the type (and also next to most of them are the extensions).
Just as other types like HumanName have FhirString properties, not native string properties (as they can have extensions anywhere in them)
However the Narrative Div type can't have extensions, it's just a primitive type.

**Comment by grahamegrieve** [comment]
maybe it's just me, but shouldn't setting the value throw an exception rather than just letting it disappear in this case?

**Comment by IlIlIllIllI** [comment]
I guess I would expect to have `Narrative.div` be of type `FhirXHTML` or something like that, and not just return a `FhirString` when it's needed to do so.  It should function like all other properties.

The code lines I've linked in the original post are just...wrong.  The properties needed to participate in the `.Children` call so they're coerced into the correct Type that they should have been all along.  I think something needs to happen here because the status quo is unexpected and could lead to weird bugs in code that is using Firely.

**Comment by ewoutkramer** [comment]
> I guess I would expect to have Narrative.div be of type FhirXHTML or something like that, and not just return a FhirString when it's needed to do so. It should function like all other properties.

Yes, that probably should have been the case. In fact, there is indeed such an XHtml type, but it is not used by the model. This is a historic oversight.
