### ISSUE TITLE
ServiceRequest.code element should be CodeableReference 

### ISSUE THREAD

**Issue by sijoxavier89** [FirelyTeam/firely-net-sdk#2376]
**ServiceRequest.code element**
As per Hl7 reference ServiceRequest.code element should be of type "CodeableReference"  for FHIR versions R4B, R5 but in firely it is still "CodeableConcept"
is there any work around for this? my code breaks when the client request have latest ServiceRequest resource

**Expected behavior**
ServiceRequest.code element should be of type "CodeableReference"

**Screenshots**
![image](https://user-images.githubusercontent.com/25562242/214950911-e70eaea5-a4ff-482e-87c9-35676b5f2f71.png)

**Version used:**
 - FHIR Version: [R4B, R5]
 - Version: [4.3.0]

**Comment by marcovisserFurore** [comment]
According to the R4B FHIR standard the element `ServiceRequest.code` is of type `CodeableConcept`. See also [here](https://www.hl7.org/fhir/R4B/servicerequest-definitions.html#ServiceRequest.code). 

For R5 we have implemented the type indeed as `CodeableConcept`, because version 4.3.0 of the SDK implements FHIR Version 5.0.0-snapshot1, where `code` still is of type `CodeableConcept`, see also [here](https://hl7.org/fhir/5.0.0-snapshot1/servicerequest-definitions.html#ServiceRequest.code).

But we are working on a new version (SDK 5.0), where we implement FHIR Version 5.0.0-snapshot3. There is the type now `CodeableReference`. Have a look [here](https://github.com/FirelyTeam/firely-net-sdk/blob/99b34105c3bda035454047c6ad3aff513d7b7a14/src/Hl7.Fhir.R5/Model/Generated/ServiceRequest.cs#L329). 

Version 5.0.0 of the SDK is already in beta2, and we plan to release it in the beginning of February 2023.

**Comment by sijoxavier89** [comment]
Thanks for clarification. Looking forward to Version 5.0.0
