### ISSUE TITLE
ArtifactSummaryGenerator.Default always uses model info for STU3

### ISSUE THREAD

**Issue by Rob5045** [FirelyTeam/firely-net-sdk#2411]
ArtifactSummaryGenerator.Default always uses model info for STU3 and therefore artifact summary generation for R4 and later will not find/fill in all summary bag properties because it fails to find the relevant resource types.

SDK: release 5.0.0
Project: Hl7.Fhir.Conformance
File: ArtifactSummaryGenerator.cs
Line: 72

`public static ArtifactSummaryGenerator Default { get; } = new ArtifactSummaryGenerator(ModelInspector.ForAssembly(typeof(IModelInfo).Assembly));`

IModelInfo is an interface defined in Hl7.Fhir.Base and it will always return the model info for STU3.

It should be:

`public static ArtifactSummaryGenerator Default { get; } = new ArtifactSummaryGenerator(ModelInfo.ModelInspector); `

**Comment by marcovisserFurore** [comment]
@Rob5045 , indeed this not correct. But this is not so easy to solve, because `ArtifactSummaryGenerator.Default` is static and cannot know which `ModelInspector` to use here. Also in a multi FHIR version solution this will not work.

So, I am thinking to make this obsolete. It is not used by our own code, and the end user (Forge for example), should define there own Default, because they know which `ModelInspector` to use. So something like this:

Somewhere in Forge (just an idea, I don't know the code for Forge):
```c#
 public class Globals 
{
     public static ArtifactSummaryGenerator Default { get; } = new ArtifactSummaryGenerator(ModelInfo.ModelInspector);
}

```

**Comment by Rob5045** [comment]
@marcovisserFurore  That is fine too.
