### ISSUE TITLE
Specifying 'Subscription.filterBy.resourceType' results in StructuralTypeException 

### ISSUE THREAD

**Issue by ms-20** [FirelyTeam/firely-net-sdk#2413]
**Describe the bug**

We are currently using Firely HL7.Fhir.R5 library's 5.0.0 version in our .net project, to construct the Subscription resource. We want to narrow the subscription topic stream by the 'Observation' resourceType by specifying it in the 'Subscription.filterBy' property.
However, while providing the 'Subscription.filterBy.resourceType' property with 'Observation', with any of the below combinations, results in a **StructuralTypeException** with the error message - **Type checking the data: Element 'filterBy' is not a contained resource, but seems to contain a resource of type 'Observation'. (at Subscription.filterBy[0])**
•	ResourceType = "Observation"
•	ResourceTypeElement = new FhirUri(http://hl7.org/fhir/StructureDefinition/Observation)
•	ResourceTypeElement = new FhirUri("Observation")

Looks like the error is caused by the fact that the field is called “resourcetype”. In json representations of FHIR resources, “resourcetype”  is also used to indicate the type of the resource. The library sees the field is present and as a result interprets it as a resource, as it is not at the top of the resource, it makes the assumption it must be a contained resource which may not be present at that location.

Hence, we think that, though we might have given the correct interpretation of the specification, there might be a mistake in the Firely library.

Is there another way of specifying the 'Subscription.filterBy.resourceType' property, that would help in resolving this error ?

**Expected behavior**
Any of the below combinations for the Subscription.filterBy.resourceType' property should have been accepted without failing with StructuralTypeException.
•	ResourceType = "Observation"
•	ResourceTypeElement = new FhirUri(http://hl7.org/fhir/StructureDefinition/Observation)
•	ResourceTypeElement = new FhirUri("Observation")

**Version used:**
 - FHIR Version: R5
 - Version: [5.0.0]

**Comment by ewoutkramer** [comment]
Our ITypedElement-based parsers have always assumed that `resourceType` is a reserved element name. And so far, it used to be (in the past, we had elements with that name that have been renamed since). It's clear that the R5 STU publication no longer sticks to that agreement. 

I don't doubt this will cause us to rethink our parsing logic, so I don't have a quick & easy fix right now.

If you are able to use our newer parsers (https://docs.fire.ly/projects/Firely-NET-SDK/parsing/system-text-json-deserialization.html) - this is a viable option. This parser will still complain, but it will continue parsing and you can ignore the error in code.

**Comment by marcovisserFurore** [comment]
Resolved by PR #2448

**Comment by brianpos** [comment]
Also note that the 5.0 SDK only had the ballot version of the FHIR v5 spec.
The 5.1.0 release also included the complete FHIR v5 models in it, and resolved this specific parsing issue.
