### ISSUE TITLE
Cannot validate fixed date value

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-net-sdk#2431]
**Describe the bug**
When validating a profile which has a fixed value set on a "date" element. The validator always flags this as an error, see https://simplifier.net/testbirthdate/patient-example/$validate

I suspect that it compares the date "1972-01-01" with the mathematical equation 1972-01-01 = 1970.

I suspect this is happening because when checking this in the FHIRPath playground on Simplifier. There it is required to put an '@' in front of a date. See: https://simplifier.net/fhirpath?filepath=MvdWExt.xml&scope=TestBirthdate@current&query=Patient.birthDate%20%3D%20(%401972-01-01)

When you remove the '@' it returns a false.

**Comment by ewoutkramer** [comment]
Looks fine to me, and the link to Simplifier shows the problem clearly.

**Comment by marcovisserFurore** [comment]
After some research the problem is the SDK method  `IsExactlyEqualTo`.  This unit test will prove that:

```c#
        [TestMethod]
        public void IsExactlyEqualToWithPrimitives()
        {
            var left = new PrimitiveElement(Date.Parse("1972-01-01"));
            var right = new PrimitiveElement(Date.Parse("1972-01-01"));

            left.IsExactlyEqualTo(right, ignoreOrder: true).Should().BeTrue();
        }
```

In the method `IsExactlyEqualTo` the generic types `T1` and `T2` are of type `object` and not of `System.Date`. And `object` does not implement  `IConvertible`. That's why the method `Convert.ChangeType` will fail.

**Comment by marcovisserFurore** [comment]
After discussing this matter with Ewout, we've identified an issue with the method `public static bool ValueEquality<T1, T2>(T1 val1, T2 val2)` within the `TypedElementExtensions` class. The problem lies in the fact that the arguments are always of type `object`, as `ITypedElement.Value` is also of type `object`.

As a result, the `IsExactlyEqualToWithPrimitives` function has never functioned correctly in certain special cases, such as `instant`, `time`, `date`, and `dateTime`.

To address this, we should consider adopting a solution similar to the one used in FhirPath, particularly the method `EqualityOperators`. It would be beneficial to combine these Equality methods into a single robust method that can be utilized by both systems effectively. This consolidation will help streamline the process and enhance the overall performance. See here a snippet of the FP method, which handles the equality better:

```c#
            // Compare primitives (or extended primitives)
            if (l != null && r != null && P.Any.TryConvert(l, out var lAny) && P.Any.TryConvert(r, out var rAny))
            {
                return IsEqualTo(lAny, rAny);
            }
            else if (l == null && r == null)
            {
                // Compare complex types (extensions on primitives are not compared, but handled (=ignored) above
                var childrenL = left!.Children();
                var childrenR = right!.Children();

                return childrenL.IsEqualTo(childrenR, compareNames: true);    // NOTE: Assumes null will never be returned when any() children exist
            }
            else
            {
                // Else, we're comparing a complex (without a value) to a primitive which (probably) should return false
                return false;
            }
```

**Comment by MatthijsvdWielen** [comment]
I would like to add to this that executing the examples in https://hl7.org/fhirpath/N1/#subtraction-2, also provides an error in the [FHIRPath playground](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20-%2024%20months). 

This can be worked around by [adding a '+' to the fhirpath](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20%2B%20-24%20months).

**Comment by ewoutkramer** [comment]
> I would like to add to this that executing the examples in https://hl7.org/fhirpath/N1/#subtraction-2, also provides an error in the [FHIRPath playground](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20-%2024%20months).
> 
> This can be worked around by [adding a '+' to the fhirpath](https://simplifier.net/fhirpath?filepath=package/CapabilityStatement-base.json&scope=hl7.fhir.r4.core@4.0.1&query=%402019-03-01%20%2B%20-24%20months).

This is another issue entirely - I was not aware we had even implemented adding quantities to dates. We should, so this needs its own issue tracker.

**Comment by ewoutkramer** [comment]
I have tried to unify the methods in `TypedElementExtensions` with those in FhirPath., but they do serve a different purpose:
* The IsExactlyEquals to for ITypedElement mimics the same function in the POCO's, and both operands must be structurally equal, no conversions done.
* The equals for FhirPath takes conversions into account, e.g. it compares FHIR Quantity with System quantities, even converting units.

We could in theory unify those given enough parameters to tune the comparison, but I am a bit afraid to break both by doing so.

**Comment by ewoutkramer** [comment]
@MatthijsvdWielen - there is one subtlety that the Fhir spec does not talk about: are two "fixed" datetimes the same if they differ in the way the specify GMT?  For now, times in "Z" and in "+00:00" are considered the same. It would otherwise be really hard to use fixed datetimes. Precision does matter, so if one specifies milliseconds and the other does not, then it is not the same fixed value.

Anyway, using fixed fully specified datetimes sounds like a very limited usecase (maybe just year is more common).
