### ISSUE TITLE
Unable to query history

### ISSUE THREAD

**Issue by azrng** [FirelyTeam/firely-net-sdk#2452]
**Is your feature request related to a problem? Please describe.**
I now want to query historical information, such as Encounter/73c19386-deed-4602-91be-7acc12ae89d9/_history, but I find that it contains validation and requests are not allowed

I look up from the documentation is to query the specified version history  :https://docs.fire.ly/projects/Firely-NET-SDK/client/crud.html#reading-an-existing-resource

thanks

**Comment by mbaltus** [comment]
The parameters you can use to search when you request history are very limited by the FHIR specification, see http://hl7.org/fhir/http.html#history.
For requesting history, you want to use the SDK's History methods instead of Read. With the `FhirClient.History`, `FhirClient.TypeHistory` and `FhirClient.WholeSystemHistory` you can specify the instant for the _since parameter, and an integer for the pagesize (i.e. _count parameter).

For your example, setting up the request would look like this if you do not add extra parameters:
```
FhirClient c = new FhirClient("[endpoint]");
Bundle myEncounterHistory = c.History("Encounter/73c19386-deed-4602-91be-7acc12ae89d9");
```
Let us know if this helps with what you are trying to achieve. If not, please elaborate on what you try to request that is not working.

**Comment by azrng** [comment]
Thank you very much for your reply, which I did not expect to receive so soon. After your guidance, I have realized my demand, inquiring the History information of the specified resource. At that time, I have found the method history, but I do not know how to pass the parameter, but I hope I can add this method to the document to help more people.

By the way, I wish to ask
1. How to query the list of all patients
2. How do I query resources based on the check item name

For these two questions, is there a corresponding interface? If not, I will consider other solutions to achieve it

**Comment by mbaltus** [comment]
The first extra question is done with a search with no parameters:
```
Bundle allPatients = c.Search<Patient>();
```

I do not know what you mean with 'check item name', but for any search that you want to do, you can look at the list of standard search parameters on the resource type page. Then you setup a SearchParams object to add to the search. For example, if I want to search the Patient resources to get a list of Patients that have a family name 'Everyman', I can do this:
```
SearchParams criteria =  new SearchParams("family", "Everyman");
Bundle patientsEveryman = c.Search<Patient>(criteria);

// add another search parameter for birthdate
criteria.Add("birthdate", "1987");
Bundle patientsEverymanBorn1987 = c.Search<Patient>(criteria);
```
The standard parameters for Patient can be found here: http://hl7.org/fhir/patient.html#search

**Comment by azrng** [comment]
Thank you for your response. Thanks to the library, I don't have to use complex xml formats
