### ISSUE TITLE
FhirPackageSource in Fhir.Validation.Legacy

### ISSUE THREAD

**Issue by darena-pjindal** [FirelyTeam/firely-net-sdk#2525]
I understand that the profile validation has been removed from the core FHIR package and moved to Fhir.Validation.Legacy in the latest SDK. In the previous version, there used to be a FhirPackageSource class that was used to load the resolver directly from a package source. It was also referenced on the blog here as the recommended approach going forward. Has that been removed from the Legacy project? Is there a recommended replacement? We are moving to use the DirectorySource but just wanted to check if there was still a way to do that.

**Comment by mmsmits** [comment]
Hi @darena-pjindal,
Thanks for reaching out. We moved FhirPackageSource out of the SDK, and into the Firely.Fhir.Packages library here:
https://github.com/FirelyTeam/Firely.Fhir.Packages/blob/develop/Firely.Fhir.Packages/Source/FhirPackageSource.cs

Because of the newer  structure of the SDK since 5.0 we couldn't manage it within the SDK anymore, without creating circular references. That's why we pulled it out and decided to maintain it in the package library instead. A much cleaner approach anyway.

We definitely recommend to use the FhirPackageSource above DirectorySource if you are looking to build and validate on top of existing FHIR packages. It's easier to maintain and is probably faster as well because of the index files.

**Comment by darena-pjindal** [comment]
Hello @mmsmits - thanks so much for sharing that. I didn't realize that there was another nuget package. I was able to use that. I am adding the old vs the new way to use FHIRPackageSource as it might help someone else too :). Thanks again 
  //Old SDK
            //var corePackageSource = new FhirPackageSource("https://packages.simplifier.net", new[] { "hl7.fhir.r4.core" });

            //New SDK
            var corePackageSource = new FhirPackageSource( new ModelInspector(FhirRelease.R4), "https://packages.simplifier.net", new[] { "hl7.fhir.r4.core" });

**Comment by ewoutkramer** [comment]
@mmsmits - should we add the name of the package to https://docs.fire.ly/projects/Firely-NET-SDK/fhir-package-source/package-source.html?

**Comment by mmsmits** [comment]
Yes, and rewrite that documentation a bit as well. I'll create a task
