### ISSUE TITLE
Run .NET package validation to detect backward compat issues.

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#2566]
Although we don't do binary compatibility between our releases, it might still be useful to implement

https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview

and double check we didn't introduce any incompatible change we did not intent to do, esp. changes to the public interface that break "compilation compatibility".

**Comment by mmsmits** [comment]
First try this in the package library/validator-api to try out.

**Comment by Kasdejong** [comment]
We tried this in the SDK, and the results were good. I will make a pull request with the validation active. From the next release onwards, we are considering using an extra tag "binary breaking change" and try to minimize the number of binary breaking changes we introduce (i.e. back to overloads instead of optional parameters to extend current functionality). The validator can help us with this.
