### ISSUE TITLE
Convenience method to extract resources from Bundle.Entry

### ISSUE THREAD

**Issue by Brilbroeder** [FirelyTeam/firely-net-sdk#2589]
Did not found convenience methods to easily extract a specific resource type from a bundle. Or did I miss something ?

If not existing, suggested extension method :
    
```
public static class BundleHelper
    {
        public static IEnumerable<T> ExtractResources<T>(this Bundle bundle) where T : DomainResource
        {
            return bundle.Entry
                .Where(x => x.Resource.TypeName == typeof(T).Name)
                .Select(x => (T)x.Resource);
        }

        public static MessageHeader? MessageHeader(this Bundle bundle)
        {
            return bundle.ExtractResources<MessageHeader>().FirstOrDefault();
        }

        public static IEnumerable<Patient> Patients(this Bundle bundle)
        {
            return bundle.ExtractResources<Patient>();
        }

        public static IEnumerable<Organization> Organizations(this Bundle bundle)
        {
            return bundle.ExtractResources<Organization>();
        }
    }
```

**Comment by ewoutkramer** [comment]
We do have an internal implementation of this, and our implementation builds a hash dictionary first, since you *probably* want to query the bundle multiple times with different types so using a dictionary made sense. But I don't know if it makes sense to do that in general. What do you think?

**Comment by ewoutkramer** [comment]
>return bundle.Entry
                .Where(x => x.Resource.TypeName == typeof(T).Name)
                .Select(x => (T)x.Resource);
                
 This might not always work, since `TypeName` is the *FHIR* name of the type, and `Type.Name` is the .NET name of the type (they may differ, though for resources, they don't).
 
 Still, this uses string comparisons, so the built-in `OfType()` would be faster, so I'd prefer this:
 
`return bundle.Entry.Select(e => e.Resource).OfType<T>();`

**Comment by mmsmits** [comment]
We think this is not necessary to add to repository. Anyone should be able to add
`bundle.Entry.Select(e => e.Resource).OfType<T>();`
To their code themselves.

However, this issue triggered us to change use IList instead of List in Bundles in a next **major** release. 
Have added a separate issue for that.

See https://github.com/FirelyTeam/firely-net-sdk/issues/2742
