### ISSUE TITLE
SnapshotSource does not reuse self-generated snapshot

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/firely-net-sdk#2802]
**Describe the bug**
SnapshotSource should return the same snapshot upon multiple retrievals. Instead, it regenerates the snapshot every time.

**To Reproduce**
1. Create a SnapshotSource, with `regenerate: true`, based on a CachedResolver
2. Get a StructureDefinition by canonical, e.g. from Element
3. Save a reference to the resulting StructureDefinition.Snapshot
4. Repeat step 2
5. Save a reference to the second resulting StructureDefinition.Snapshot
6. Observe that both references are not the same.

**Expected behavior**
When the SnapshotSource has generated (by the Generator) a snapshot, it is marked as `IsCreatedBySnapshotGenerator()`, and it should not be re-generated again upon subsequent retrievals.

**Screenshots**
n/a

**Version used:**
 - FHIR Version: All
 - Version: 5.8.1

**Additional context**
-

**Comment by ewoutkramer** [comment]
This is not a bug, but a feature. Set regenerate to false to get the desired behaviour. I must be missing something ;-)

**Comment by ewoutkramer** [comment]
Offline discussion added some new insights:

* The current Regenerate options will always regenerate a new snapshot, even though the documentation suggests it will not repeatedly do so. 
* Setting this to `true` seems to be not really useful, since -except for some testing usecases- it's not clear why you'd like to snapshot again and again.
* Setting it to `false` is what most people want: generate the snapshot if it does not exist or re-generate it when it's not done by our tools. This is the default and many tools will depend on it. 
* It is not possible to allow snapshots created by other tools (probably: the java tooling) at this moment.
* Since whether a snapshot is "ours" is done using an in-memory annotation, initially every snapshot will be regenerated, the flag only ensures we're not doing it twice.

If we'd apply #2803 we will certainly get regressions, since this PR will cause `true` to result in the old behaviour for false, and `false` (still the default) will cause 3rd-party snapshots to be used instead of being regenerated. 

A first conclusion might be that the current regenerate option is not particularly useful (we'd be better of without it), is not documented clearly and does not allow for 3rd-party snapshots to be used.  We should obsolete it and introduce a  more explicit setting. Basically there are only two cases:

* Add a snapshot if there is none or use whatever is there (new behaviour)
* Regenerate snapshot once to ensure it is "ours" (and/or at least updated to the lastest version) (current default behaviour)
* Maybe: heuristically try to determine whether the snapshot is ours (there must be obvious differences) and then avoid regenerating it.
