### ISSUE TITLE
Refactor the Poco serializers to work against Base

### ISSUE THREAD

**Issue by Kasdejong** [FirelyTeam/firely-net-sdk#2917]
Change the serializers to use the new IScopedNode interface.

**Comment by ewoutkramer** [comment]
I am not sure this is beneficial. It allows us to cover the minor usecase of using the parents element name when serializing subtrees of resources (which officially does not exist) but otherwise, serialization does not need a parent, and so the current itypedelement based direct implementation on pocos would introduce overhead to serialization (including calculation Value) for little profit. If we want to move away from using IROD we should probably just write the serializers against POCO directly, it internally assumes it is using pocos anyway.

**Comment by ewoutkramer** [comment]
Another note: to make it possible to maintain correct XML ordering, we need to make sure the XML poco parser  annotates the nodes with the order, so it can be maintained. We can also add an `AddWithOrder` extension method to base, so XML users can add elements to (dynamic) resources AND influence the ordering/insert new elements between existing elements.

**Comment by Kasdejong** [comment]
We should also extend IFhirSerializationEngine to allow for "Base" (de)serializing

**Comment by ewoutkramer** [comment]
* I have not added overloads for readers/writers to the IFhirSerializationEngine, since it makes implementing that interface harder.  If people need more power to work against streams, you can always use the PocoXml/PocoJson serializers directly instead of via the interface.
* We have added extension methods for IFhirSerializationEngine that allow you to serialize to streams for resources and, via an explicit overload, also via Base (elements in the tree).
* The BaseFhirXmlSerializer will serialize an element with a root specifying its typename, unless an explicit name is given.

⚠  I have changed the PocoXml/Json serializers to work against Base, not IReadOnlyDictionary<>

⚠ I have removed the following methods that were already obsolete:
* The `FhirJsonConverter() constructors, use the ForFhir() extension methods on the JsonSerializerOptions instead.
