### ISSUE TITLE
[FhirClient] Provide a way to manipulate the body in OnBeforeRequest/OnAfterResponse

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-net-sdk#478]
To be able to implement content encryption, we need to be able to encrypt (on the way out) en decrypt (on the way in) the data flowing through the FhirClient.

Currently, we do have events to support this (and manipulate the *headers*), but these won't allow you to manipulate the body (technically, you can manipute the byte array passed into the event, but that would not allow you to resize it)

Maybe we should introduce additional callbacks that would allow you to manipulate the body in addition to the current callbacks (which would not require us to break the current interface)

**Comment by ewoutkramer** [comment]
In fact, this originated from a discussion of how to implement

https://tools.ietf.org/html/rfc8188

in FHIR

**Comment by brianpos** [comment]
This would need to be on both sides, to encrypt on write, and also to decrypt on read

**Comment by kennethmyhra** [comment]
@ewoutkramer @brianpos I have referenced a commit to this issue which should solve it, it's based on the code I retrieved from Brian at FHIR Dev Days.

I would though like to see this implemented it in a fashion that would give me more control over the request/response pipeline much in the same way as is done with MessageHandlers/DelegateHandlers in ASP.NET, it will then allow me to add the required handlers when setting up the FhirClient. For example when encrypting it would make sense to encrypt after you have compressed the content rather than before.

Maybe the request/response pipeline is something that could be considered when implementing issue #480 as it seems to me it would break the current implementation.

**Comment by ewoutkramer** [comment]
Yes, connecting this issue with #480 makes sense, since we only need to break the interface once, and also it is likely whatever pipelining we make up will need to be redone/retested when we switch to the new http client...

**Comment by kennethmyhra** [comment]
Ewout, saw your comment in #480 in regards to creating a new FhirWebClient class. Do you want me to issue a PR for c8dfc8e (referenced above) into the current FhirClient? If any changes are required before pulling let me know and I will fix them.

**Comment by ewoutkramer** [comment]
Yes, that seems to make sense to me.

**Comment by marcovisserFurore** [comment]
Solved by the introduction of the new FhirClient (version SDK 2.0)
