### ISSUE TITLE
ObjectListExtensions.OfType should ignore null values

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#647]
Concerning the extension method `ObjectListExtensions.OfType` in the Hl7.Fhir.Support library:

1) Why this custom method, as LINQ also provides a (generic) method `OfType<T>` with same behavior out of the box?
2) The LINQ `OfType<T>` method uses the `is` operator, which automatically skips/excludes `null` values but includes subclasses. The custom method compares runtime types, which throws an exception for `null` values and excludes subclasses.

Suggestions:
1) Remove this method, use LINQ instead
2) Or rewrite the method to behave exactly the same as the LINQ method (using `is` operator)
3) Or rename this method to e.g. OfExactType (only if the API depends on such behavior)

**Comment by ewoutkramer** [comment]
We cannot use the LINQ method here, since it's not the same.  OfType<T> in LINQ takes a compile-time specified generic parameter, this method takes a variable type parameter, which is passed at runtime  and cannot be used with 'is'.

The behaviour of 'is' can be simulated with Type.IsAssignableFrom(), which is however much slower than direct type comparisons.

I do agree this method is way too specific to be a public extension on IEnumerable<object>, so I will consider inlining this, since it's hardly used.

**Comment by wmrutten** [comment]
Agreed, inlining seems appropriate here.

**Comment by mmsmits** [comment]
Decided to remove ```ObjectListExtensions``` entirely + tests. Since this is not used anyway.
