### ISSUE TITLE
Need to add more values to enum v3CodeSystemConfidentiality

### ISSUE THREAD

**Issue by SWATOPLUS** [FirelyTeam/firely-net-sdk#848]
Need to add more values to enum v3CodeSystemConfidentiality

https://github.com/ewoutkramer/fhir-net-api/blob/master/src/Hl7.Fhir.Core/Model/Generated/Composition.cs

Specification:

https://www.hl7.org/fhir/DSTU2/v3/Confidentiality/index.html

**Comment by SWATOPLUS** [comment]
I found it bacause spark DSTU2 doesn't support it, and it refers to Hl7.Fhir.DSTU2 0.96.0 nuget.

**Comment by brianpos** [comment]
The master branch is for DSTU2, check the STU3 related branches like develop-stu3

**Comment by brianpos** [comment]
Sorry, miss read issue.
Did you mean the codes B, D...?

**Comment by SWATOPLUS** [comment]
Body parsing failed: Literal 'I' is not a valid value for enumeration 'v3CodeSystemConfidentiality'

**Comment by SWATOPLUS** [comment]
I run autotest for spark https://projectcrucible.org
And have this issue, the problem is in lacks of enum items.

**Comment by SWATOPLUS** [comment]
There are also same mistake. Crucible generates random enum value and thatswhy it is dufficult to repoduce.

**Comment by brianpos** [comment]
That's a known issue with crucibles random generation. Doesn't always produce truly valid fhir instances.

**Comment by SWATOPLUS** [comment]
As I understand crucible **should** generate values B, D, SDV of v3CodeSystemConfidentiality at DSTU2 due to this document:
https://www.hl7.org/fhir/DSTU2/v3/Confidentiality/index.html#definition
But nuget Hl7.Fhir.DSTU2 doesn't support it. So value B, D, SDV should be added to v3CodeSystemConfidentiality enum here:
https://github.com/ewoutkramer/fhir-net-api/blob/master/src/Hl7.Fhir.Core/Model/Generated/Composition.cs#L95
They are marked as deprecated in specification, but it should exist in enum. So I think this is not issue of crucible.

**Comment by ewoutkramer** [comment]
These enumerations are generated from files delivered to us by HL7 - so we reflect 100% the source files from HL7. Interestingly, the "B" code is in this file (expansions.xml), as is "SDV" and "D" are in the valueset, but not in the expansion of the valueset.  We are totally dependent on the expansion - clearly this expansion is not including the "deprecated" codes.

That's hard to fix, since we cannot normally use the unexpanded valueset specification. But for now, you can configure the parser  (FhirClient.ParserSettings) and set "AllowUnrecognizedEnums", see here for more details: http://docs.simplifier.net/fhirnetapi/parsing/poco-parsing.html

**Comment by ewoutkramer** [comment]
Should be fixed by now by HL7. If it is not, it won't be. Either way, there's nothing we can do here as we're using the provided expansions and I don't feel like doing that myself.
