### ISSUE TITLE
StreamNavigators should also return Bundle resources

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#939]
The `Xml/JsonStreamNavigator` classes implement special behavior for `Bundle` resources; the navigators return the contained Bundle entries, but not the Bundle itself.

The `DirectorySource` class uses the NavigatorStream classes to harvest summary information from the content directory. As a result of the above limiation, you cannot access Bundle resources on disk using DirectorySource.

Request:
- Allow NavigatorStream to also return Bundle resources
- (?) implement configuration option to control behavior
- Update `DirectorySource` to enable the new behavior and expose Bundle resources

**Comment by ewoutkramer** [comment]
We're moving slowly unto the path where the classes implementing IResourceResolver do more than they were designed for, which is return things that are conformance resources as resolvable by canonical.  
For other files, I originally designed the IArtifactSource interface.  The advantage of this separation is that we let the client make a structural decision on whether to activate behaviour connected to resolving conformance stuff (one interface) or fetch any source file (IArtifactSource) - instead of making this a dynamic choice using a setting or extra parameter on a resolve call.   Also, since these other artifacts don't always have a canonical, I think we're confounding two different beasts and purposes....

The disadvantage of a dynamic choice is that setting it on the resolvers's settings is too coarse (you want it probably on a ca

**Comment by mmsmits** [comment]
We will not be implementing this anymore, since we are now using PackageSource for most work
