### ISSUE TITLE
Allow FHIRPath validation against StructureDefinition

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/firely-net-sdk#942]
Forge tries to verify the extension context of profile extensions, i.e. match the context of the selected extension definition to the selected parent element in the user profile.
R4 introduces the option to define extension context as a FHIRPath expression.
To verify such an expression, Forge needs to execute `CompiledExpression.Predicate()` against the target `StructureDefinition` resource.
However there doesn't seem to be an easy way to inject the user's StructureDefinition instance into the Predicate() call...?
Note: usually a FHIRPath expression is being evaluated against a concrete `Resource` instance. However in this case, we don't have an instance, only a `StructureDefinition`.

**Comment by brianpos** [comment]
Michel, you might look at my code that validates fhirpath expressions for questionnaires in the fhirpath tester. Its not complete, but it does 90% of the stuff that I've needed.
https://github.com/brianpos/FhirPathTester/blob/8f170d0faabf28516a491b040997089cf7662324/WPF/MainWindow.xaml.cs#L493
Could adapt this class to use the structuredefinition navigator instead of the classmappings

**Comment by ewoutkramer** [comment]
What you need is something that I am in the process of adding, because it's completely comparable to evaluating a slice discriminator against a StructureDefinition.

It's here: https://github.com/FirelyTeam/fhir-net-api/blob/feature/rework-elementdefinitionsummary/src/Hl7.Fhir.Specification/Specification/Navigation/FhirPath/DiscriminatorInterpreter.cs

This is an implementation of FhirPath that works on top of definitions, instead of instances.  The Fhir spec has a description of the subset of FhirPath for which this works (and which should be enough to cover the StructureDefinition.context) here: http://hl7.org/fhir/profiling.html#discriminator

Since the code linked to above is part of a bigger PR that may never get pulled, I need to get this part out of there and create a separate pull request.

**Comment by ewoutkramer** [comment]
This is done, it's part of the SDK and is called `StructureDefinitionWalker`. It's used to pre-compute the fixed values/bindings etc when doing slicing.  It can be used to walk the context part into a given structuredefinition, just as asked here.
