### ISSUE TITLE
Remove ConstraintBestPractices.Ignore option in v2.0

### ISSUE THREAD

**Issue by gstoian** [FirelyTeam/firely-net-sdk#987]
The logic for the constraints marked as Best Practices has been implemented in #986 and the initial item was this one #796 . 

Because the old behavior didn't take in consideration these constraints during the validation process, the Ignore option has been added, so the existing outcome wouldn't change for the users.

In 2.0 this behavior needs to be fixed, by handling these constraints without ignoring them.

**Comment by ewoutkramer** [comment]
I think we should make this change at the same time as doing the new validator.  Indeed, some things that are valid now, might fail a best-practice and so give an error once we remove the "Ignore" option (or no longer make it the default at least).

I would also review to rename "Enable" and "Disable", since "Enable" means failing a best-practice is turned into an error, and "Disable" means turning it into a Warning.  This is done by changing the constraint severity level - since this should be a static bit of data (and will be read-only in the new validator), I don't like us changing the severity property of the ElementDefinition.

**Comment by ewoutkramer** [comment]
If you look at the definition at http://hl7.org/fhir/extension-elementdefinition-bestpractice.html, you will see

"Validators may/should offer implementers the choice to enforce invariants labeled as 'best practice' as errors not warnings."

So, we should probably have a setting of turn a best-practice into an error or warning (and maybe call the settings that way).
